name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-rust-app:${{ github.sha }} .

      - name: Stop and remove existing container
        run: |
          ssh -i <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'docker stop my-rust-container || true'
          ssh -i <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'docker rm my-rust-container || true'

      - name: Run new Docker container
        run: |
          ssh -i <(echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}") ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'docker run -d --name my-rust-container -p 8000:8080 my-rust-app:${{ github.sha }}'
