name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t my-rust-app:${{ github.sha }} .

      - name: Decode and save private key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | base64 --decode > ssh_key.pem
          chmod 600 ssh_key.pem

      - name: Stop and remove existing container
        run: |
          ssh -i ssh_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'docker stop zealous_bartik || true'
          ssh -i ssh_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'docker rm zealous_bartik || true'

      - name: Run new Docker container
        run: |
          ssh -i ssh_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} 'docker run -d --name zealous_bartik -p 8080:8080 my-rust-app:${{ github.sha }}'
