name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > workflow-rust.pem
          chmod 600 workflow-rust.pem

      - name: Debug SSH Connection
        run: ssh -i workflow-rust.pem -vvv ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'echo Debugging SSH connection'

      - name: Build Docker image
        run: docker build -t rust-app:${{ github.sha }} .

      - name: Stop and remove existing container
        run: |
          ssh -i workflow-rust.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'docker stop amazing_diffie || true'
          ssh -i workflow-rust.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'docker rm amazing_diffie || true'
          rm -f workflow-rust.pem

      - name: Run new Docker container
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > workflow-rust.pem
          chmod 600 workflow-rust.pem
          ssh -i workflow-rust.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'docker run -d --name amazing_diffie -p 8080:8080 rust-app:${{ github.sha }}'
          rm -f workflow-rust.pem
